const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  isElectron:    true,
  openDirectory: (opts)       => ipcRenderer.invoke('dialog:openDirectory', opts),
  openFiles:     (opts)       => ipcRenderer.invoke('dialog:openFiles', opts),
  readdir:       (p)          => ipcRenderer.invoke('fs:readdir', p),
  exists:        (p)          => ipcRenderer.invoke('fs:exists', p),
  mkdir:         (p)          => ipcRenderer.invoke('fs:mkdir', p),
  readFile:      (p)          => ipcRenderer.invoke('fs:readFile', p),
  writeFile:     (p, data)    => ipcRenderer.invoke('fs:writeFile', p, data),
  copyFile:      (src, dest)  => ipcRenderer.invoke('fs:copyFile', src, dest),
  unlink:        (p)          => ipcRenderer.invoke('fs:unlink', p),
  stat:          (p)          => ipcRenderer.invoke('fs:stat', p),
  readPartial:   (p, off, len)=> ipcRenderer.invoke('fs:readPartial', p, off, len),
  scanVpx:       (p)          => ipcRenderer.invoke('fs:scanVpx', p),
  listZip:       (p)          => ipcRenderer.invoke('fs:listZip', p),
  extractZipFlat:   (p, dest, exts, opts)   => ipcRenderer.invoke('fs:extractZipFlat', p, dest, exts, opts),
  extractZipNested: (p, dest, prefix)       => ipcRenderer.invoke('fs:extractZipNested', p, dest, prefix),
  listRar:          (p)                     => ipcRenderer.invoke('fs:listRar', p),
  extractRarFlat:   (p, dest, exts, opts)   => ipcRenderer.invoke('fs:extractRarFlat', p, dest, exts, opts),
  extractRarNested: (p, dest, prefix)       => ipcRenderer.invoke('fs:extractRarNested', p, dest, prefix),
  extractArchiveMedias: (p, popmedia, vpxBase) => ipcRenderer.invoke('fs:extractArchiveMedias', p, popmedia, vpxBase),
  onExtractProgress:  (cb) => ipcRenderer.on('extract:progress', (_, d) => cb(d)),
  offExtractProgress: ()  => ipcRenderer.removeAllListeners('extract:progress'),
  watchStaging:    (p) => ipcRenderer.invoke('fs:watchStaging', p),
  onStagingCount:  (cb) => ipcRenderer.on('staging:count', (_, n) => cb(n)),
  offStagingCount: ()  => ipcRenderer.removeAllListeners('staging:count'),
  confirm:          (msg) => ipcRenderer.invoke('dialog:confirm', msg),
  showItemInFolder: (p) => ipcRenderer.invoke('shell:showItemInFolder', p),
  openPath:         (p) => ipcRenderer.invoke('shell:openPath', p),
  downloadFile:     (url, dest) => ipcRenderer.invoke('download:file', url, dest),
  onDownloadProgress:  (cb) => ipcRenderer.on('download:progress', (_, d) => cb(d)),
  offDownloadProgress: ()  => ipcRenderer.removeAllListeners('download:progress'),
  openDownloadWindow:  (url, dest, type) => ipcRenderer.invoke('auth:openDownloadWindow', url, dest, type),
  hasCookiesForUrl:    (url) => ipcRenderer.invoke('auth:hasCookiesForUrl', url),
  clearCookiesForUrl:  (url) => ipcRenderer.invoke('auth:clearCookiesForUrl', url),
});
